import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Script from "next/sript";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "iDesign",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
<script async src="https://www.googletagmanager.com/gtag/js?id=G-SCZ9P4PQ21"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-SCZ9P4PQ21');
</script>
      <body className={`${inter.className} `}>
        <Navbar />
        <div className="h-[calc(100vh-70px)]">{children}</div>
      </body>
    </html>
  );
}
