import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata = {
  title: "iDesign",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   

      <body className={`${inter.className} `}>
        <Navbar />
        <div className="h-[calc(100vh-70px)]">{children}</div>
      </body>
  <GoogleAnalytics gaId="G-SCZ9P4PQ21" />
    </html>
  );
}
